### ISSUE TITLE
Konversation 2.0

### ISSUE THREAD

**Issue by ShalokShalom** [Nordgedanken/Morpheus#59]
You know Konversation 2 is doing quite the same?

https://blogs.kde.org/2017/09/05/konversation-2x-2018-new-user-interface-matrix-support-mobile-version

**Comment by MTRNord** [comment]
Well first of All I never one that existed as a client :) but my Design is a bit different and this Client has a Windows first Focus. So I guess the KDE Client is more Linux first and the Design they have (and the Design goal I have for the future) are different too. My client is way closer to nheko. And yeah of course there are many matrix clients :) this project exists currently for 3 Personal reasons: learn qt, learn how to do "Real" applications, learn the Matrix protocol.

Or what exactly do you want to hear as a awnser. Of course matrix has plenty of clients. (because it is open)

**Comment by ShalokShalom** [comment]
Just trying to prevent you from unnecessary effort. :)

Good luck :D
